export var global = {
	// url: 'http://www.backend-rendicion-de-cuentas.subredsur.gov.co/public/api/',
	url: 'http://info-utilitario.subredsur.gov.co/public/api/',
	roles: [
		{id:0, value: 'ADMIN_ROLE', name: 'Administrador'},
		{id:1, value: 'USER_ROLE', name: 'Usuario'},
		{id:2, value: 'REPORTS_ROLE', name: 'Informes'}
	],
	area: [
		{id:0, value: 'ADMINISTRATIVA'},
		{id:1, value: 'APH'},
		{id:2, value: 'CALIDAD'},
		{id:3, value: 'CONSULTA EXTERNA - ABRAHAM LINCON'},
		{id:4, value: 'ESPACIO VIVIENDA'},
		{id:5, value: 'FACTURACIÓN'},
		{id:6, value: 'HOSPITALIZACIÓN'},
		{id:7, value: 'SIRC'},
		{id:8, value: 'TERAPIA RESPIRATORIA'},
		{id:9, value: 'TRANSLADOS INTERNOS'},
		{id:10, value: 'UCI NEONATOS'},
		{id:11, value: 'UNIDAD NEONATOS'},
		{id:12, value: 'URGENCIAS'},
		{id:13, value: 'VIGILANCIA SANITÁRIA'},
		{id:14, value: 'ORTOPEDIA'},
		{id:15, value: 'LABORATORIO'},
		{id:16, value: 'ODONTOLOGÍA'},
	],
	arls: [
		{id: 0, value: 'SURA'}
	],
	aseguradoras: [
		{id: 0, value: 'ALIANSALUD'},
		{id: 1, value: 'COMPENSAR'},
		{id: 2, value: 'FAMISANAR'},
		{id: 3, value: 'MEDIMAS'},
		{id: 4, value: 'NUEVA EPS'},
		{id: 5, value: 'SALUD TOTAL'},
		{id: 6, value: 'SANITAS'},
		{id: 7, value: 'SURA'},
	],
	estados: [
		{id: 0, value: 'CUARENTENA'},
		{id: 1, value: 'HOSPITALIZADO'},
		{id: 2, value: 'RECUPERADO'},
		{id: 3, value: 'UCI'},
		],
	manejos: [
		{id: 0, value: 'AMBULATORIO'},
		{id: 1, value: 'HOSPITALIZADO'},	
	],
	nexos: [
		{id: 0, value: 'DESCONOCIDO'},
		{id: 1, value: 'FAMILIAR'},	
		{id: 2, value: 'LABORAL'},	
		{id: 3, value: 'LABORAL DE OTRA ENTIDAD'},	
	],
	perfil: [
		{id:0, value: 'AUXILIAR ADMINISTRATIVO'},
		{id:1, value: 'AUXILIAR DE ENFERMERÍA'},
		{id:2, value: 'CONDUCTOR'},
		{id:3, value: 'CONDUCTOR APH'},
		{id:4, value: 'ENFERMERA'},
		{id:5, value: 'ENFERMERA SSO'},
		{id:6, value: 'MÉDICO AUDITOR'},
		{id:7, value: 'MÉDICO GENERAL'},
		{id:8, value: 'MÉDICO INTERNISTA'},
		{id:9, value: 'MÉDICO PEDIATRA'},
		{id:10, value: 'MÉDICO SSO'},
		{id:11, value: 'MÉDICO VETERINARIO'},
		{id:12, value: 'PROFESIONAL DE ENLACE'},
		{id:13, value: 'TERAPEUTA RESPIRATORIA'},
		{id:14, value: 'MÉDICO ESPECIALISTA'},
		{id:15, value: 'MENSAJERO'},
		{id:16, value: 'AUXILIAR DE ODONTOLOGÍA'},
	],
	respuestas: [
		{id: 0, value: 'SI'},
		{id: 1, value: 'NO'},
	],
	sexo: [
		{id: 0, value: 'FEMENINO'},
		{id: 1, value: 'MASCULINO'},
	],
	tipoDocumento: [
		{ id: 0, value: 'CÉDULA DE CIUDADANIA' }
	],
	tipoVinculacion: [
		{ id: 0, value: 'OPS' },
		{ id: 1, value: 'PLANTA' },
	],
	unidades: [
		{ id: 0, value: 'USS AMBULATORIA ABRAHAM LINCON' },
		{ id: 1, value: 'USS BETANIA' },
		{ id: 2, value: 'USS CANDELARIA  I' },
		{ id: 3, value: 'USS DANUBIO AZUL' },
		{ id: 4, value: 'USS ISMAEL PERDOMO' },
		{ id: 5, value: 'USS JERUSALEN' },
		{ id: 6, value: 'USS LA ESTRELLA' },
		{ id: 7, value: 'USS LA FLORA' },
		{ id: 8, value: 'USS LA REFORMA' },
		{ id: 9, value: 'USS LIMONAR' },
		{ id: 10, value: 'USS LORENZO ALCANTUZ' },
		{ id: 11, value: 'USS MEISSEN' },
		{ id: 12, value: 'USS PASQUILLA' },
		{ id: 13, value: 'USS POTOSÍ' },
		{ id: 14, value: 'USS SAN BENITO' },
		{ id: 15, value: 'USS SANTA LIBRADA  I' },
		{ id: 16, value: 'USS SANTA MARTA' },
		{ id: 17, value: 'USS TUNAL' },
		{ id: 18, value: 'USS TUNJUELITO' },
		{ id: 19, value: 'USS YOMASA' },
		{ id: 20, value: 'USS CASA DE TEJA' },
		{ id: 21, value: 'USS DESTINO' },
		{ id: 22, value: 'USS EL CARMEN - MATERNO INFANTIL' },
		{ id: 23, value: 'USS ISLA DEL SOL' },
		{ id: 24, value: 'USS MANUELA BELTRÁN  I' },
		{ id: 25, value: 'USS MARICHUELA' },
		{ id: 26, value: 'USS MOCHUELO' },
		{ id: 27, value: 'USS NAZARETH' },
		{ id: 28, value: 'USS PARAÍSO' },
		{ id: 29, value: 'USS SAN FRANCISCO' },
		{ id: 30, value: 'USS SAN ISIDRO' },
		{ id: 31, value: 'USS SAN JUAN DE SUMAPAZ' },
		{ id: 32, value: 'USS SIERRA MORENA' },
		{ id: 33, value: 'USS USME' },
		{ id: 34, value: 'USS VISTA HERMOSA' },
		{ id: 35, value: 'SIRC' },
		{ id: 36, value: 'PIC' },
	],
}