export class Caso {
    constructor(
        public id: number,
        public patients_id: number,
        public clasificacionCaso: number,
        public numeroRadicado: number,
        public fechaNotificacion: string,
        public fechaRecepcion: string,
        public UPGD_id: number,
        public fechaAsignacionCaso: string,
        public fechaConsultaPersona: string,
        public fechaHospitalizacion: string,
        public fechaAsignacion: string,
        public asignacionProfesional: number,
        public asignacionAuxiliar: number,
        public IEC: number,
        public fechaIEC: string,
        public antecedenteViaje: number,
        public lugarViaje: string,
        public fuenteContagio: string,
        public fechaInicioSintomas: string,
        public fechaDiagnostico: string,
        public estadoPersona: number,
        public estadoFinal: number,
    ){}
}