export class Caso {
    constructor(
        public id: number,
        public clasificacionCaso: number,
        public numeroRadicado: number,
        public fechaNotificacion: string,
        public fechaRecepcion: string,
        public UPGD_id: number,
        public fechaAsignacionCaso: string,
        public fechaConsultaPersona: string,
        public fechaHospitalizacion: string,
        public fechaAsignacion: string,
        public asignacionProfesionalGrupo: string,
        public asignacionAuxiliarGrupo: string,
        public IEC: number,
        public fechaIEC: string,
        public user_id: number,
        public primerNombre: string,
        public segundoNombre: string,
        public primerApellido: string,
        public segundoApellido: string,
        public tipoDocumento: number,
        public documento: number,
        public edad: number,
        public unidadMedida: number,
        public sexo: number,
        public direccion: string,
        public barrio: string,
		public UPZ_id: number,
		public nacionalidad: string,
        public telefono: number,
        public insurers_id: number,
        public antecedenteViaje: number,
        public lugarViaje: string,
        public ocupacion: string,
        public fuenteContagio: string,
        public fechaInicioSintomas: string,
        public fechaDiagnostico: string,
        public estadoPersona: number,
    ){}
}