export class Collaborators{
	constructor(
		public id: number,
		public idRelacionado: number,
		public nombre: string,
		public tipoDocumento: number,
		public documento: number,
		public sexo: string,
		public fechaNacimiento: string,
		public edad: number,
		public telefono: number,
		public arl: string,
		public aseguradora: string,
		public direccion: string,
		public perfil: number,
		public vinculacion: number,
		public area: number,
		public unidad: number,

		public fechaIngreso: string,
		public fechaEgreso: string,
		public fechaSintomas: string,
		public fiebre: number,
		public malestarGeneral: number,
		public disnea: number,
		public odinia: number,
		public gastrointestinales: number,
		public estornudo: number,
		public mialgias: number,

		public riesgoEndogeno: string,
		public riesgoExogeno: string,
		public factoresExposicion: string,
		public manejo: number,
		public remitido: string,
		public fechaTomaMuestra: string,
		public fechaResultado: string,
		public diasTranscurridos: number,
		public contagiado: number,
		public nexo: string,
		public primerSeguimiento: string,
		public nombrePrimerSeguimiento: string,
		public segundoSeguimiento: string,
		public nombreSegundoSeguimiento: string,
		public estado: number,
		public trabajo: number,
		public fechaSegundaPrueba: string,
		public observaciones: string,
	){}
}